#ifndef APPINFO_DE_H
#define APPINFO_DE

#define VER_PRODUCTNAME_STR         "Vadehavsordbog"
#define VER_FILEDESCRIPTION_STR		VER_PRODUCTNAME_STR
#define VER_INTERNALNAME_STR        VER_PRODUCTNAME_STR
#define VER_ORIGINALFILENAME_STR    VER_PRODUCTNAME_STR ".exe"
#define VER_LANGUAGE_CODE           0x0406

#endif // APPINFO_DE_H
